### PR TITLE
Enable host utility kw scan using PHONY method

### PR DESCRIPTION
**Pull request by sgnanase**
Tracked-On: OAM-91951
Signed-off-by: Babu B, Ramesh <ramesh.babu.b@intel.com>

### CODE REVIEW

**Review by rbabub — APPROVED** [review]
Looks good to me.

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
Please remove KW scan from commit message. 

This patch is about building host utility using PHONY method

**Review by JeevakaPrabu — APPROVED** [review]

**Review by swaroopbalan — APPROVED** [review]

**Review by balajim001 — APPROVED** [review]
Looks good to me

**Review by rbabub — APPROVED** [review]
Looks good to me.

**Pull request merged**
